// Copies the Material Symbols (Apache-2.0) icons Kora uses into public/icons so the app ships only
// the SVGs it needs and loads nothing from third-party origins (keeps the CSP strict).
// Usage: node scripts/copy-icons.mjs   (add a name to ICONS, then re-run)
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = [
  'account_circle',
  'account_tree',
  'add',
  'admin_panel_settings',
  'approval',
  'arrow_back',
  'arrow_downward',
  'arrow_forward',
  'arrow_upward',
  'summarize',
  'assignment',
  'attach_file',
  'badge',
  'block',
  'bookmark',
  'bug_report',
  'build',
  'cancel',
  'check',
  'check_box',
  'check_circle',
  'chevron_right',
  'close',
  'contrast',
  'corporate_fare',
  'dark_mode',
  'dashboard',
  'delete',
  'description',
  'do_not_disturb_on',
  'domain',
  'done_all',
  'download',
  'drag_handle',
  'drag_indicator',
  'dynamic_feed',
  'edit',
  'error',
  'event_busy',
  'fact_check',
  'flag',
  'folder_open',
  'format_indent_decrease',
  'format_indent_increase',
  'group',
  'history',
  'image',
  'info',
  'inventory_2',
  'keyboard_arrow_down',
  'keyboard_arrow_up',
  'keyboard_double_arrow_up',
  'language',
  'light_mode',
  'link',
  'link_off',
  'lock',
  'lock_reset',
  'login',
  'logout',
  'mail',
  'menu',
  'more_vert',
  'notifications',
  'palette',
  'person',
  'person_add',
  'picture_as_pdf',
  'print',
  'priority_high',
  'refresh',
  'schedule',
  'search',
  'send',
  'settings',
  'swap_horiz',
  'table_chart',
  'table_rows',
  'thumb_down',
  'thumb_up',
  'timeline',
  'translate',
  'unarchive',
  'undo',
  'unfold_less',
  'unfold_more',
  'upload_file',
  'verified',
  'view_kanban',
  'visibility',
  'visibility_off',
  'warning',
  'wifi_off',
  'work',
];

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'node_modules/@material-symbols/svg-400/outlined');
const target = join(root, 'public/icons');
mkdirSync(target, { recursive: true });

for (const name of ICONS) {
  const file = join(source, `${name}.svg`);
  if (!existsSync(file)) throw new Error(`Unknown icon: ${name}`);
  copyFileSync(file, join(target, `${name}.svg`));
}
console.log(`Copied ${ICONS.length} icons to public/icons`);
